# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='shorthand',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
        migrations.AddField(
            model_name='competition',
            name='shorthand',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
        migrations.AddField(
            model_name='major',
            name='shorthand',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
