# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 18:59
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180317_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='shorthand',
            field=models.CharField(default=app.models.__str__, max_length=255),
        ),
        migrations.AlterField(
            model_name='competition',
            name='shorthand',
            field=models.CharField(default=app.models.__str__, max_length=255),
        ),
        migrations.AlterField(
            model_name='major',
            name='shorthand',
            field=models.CharField(default=app.models.__str__, max_length=255),
        ),
    ]
