# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180317_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='shorthand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='shorthand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='shorthand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
