# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180317_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='shorthand',
            field=models.CharField(default='N/A', help_text='Ex: HPV, CE, Baja. If no shorthand available reenter the title.', max_length=255),
        ),
        migrations.AlterField(
            model_name='competition',
            name='shorthand',
            field=models.CharField(default='N/A', help_text='Ex: HPV, CE, Baja. If no shorthand available reenter the title.', max_length=255),
        ),
        migrations.AlterField(
            model_name='major',
            name='shorthand',
            field=models.CharField(default='N/A', help_text='Ex: HPV, CE, Baja. If no shorthand available reenter the title.', max_length=255),
        ),
    ]
