# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180321_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='picture',
            field=models.ImageField(default='gearbg.png', upload_to='competitions'),
        ),
    ]
